### ISSUE TITLE
conduit-throttle-0.3.1.0 test suite build failure with conduit-1.3

### ISSUE THREAD

**Issue by DanBurton** [mtesseract/conduit-throttle#12]
As seen on the Stackage build server:

```
[1 of 4] Compiling Data.Conduit.Throttle.MBC.Test ( tests/Data/Conduit/Throttle/MBC/Test.hs, dist/build/conduit-test/conduit-test-tmp/Data/Conduit/Throttle/MBC/Test.o )

tests/Data/Conduit/Throttle/MBC/Test.hs:37:5: error:
    • No instance for (Control.Monad.Trans.Control.MonadBaseControl
                         IO (ResourceT IO))
        arising from a use of ‘ConduitThrottle.throttleProducer’
    • In the first argument of ‘(=$=&)’, namely
        ‘ConduitThrottle.throttleProducer conf (sourceList [1 .. 5])’
      In the second argument of ‘($)’, namely
        ‘ConduitThrottle.throttleProducer conf (sourceList [1 .. 5])
           =$=& printC’
      In a stmt of a 'do' block:
        runResourceT . runCConduit
          $ ConduitThrottle.throttleProducer conf (sourceList [1 .. 5])
              =$=& printC
   |
37 |     ConduitThrottle.throttleProducer conf (sourceList [1..5]) =$=& printC
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I was able to reproduce locally like so:

```bash
stack unpack conduit-throttle-0.3.1.0 && cd conduit-throttle-0.3.1.0
edit stack.yaml # add the following stack.yaml
stack test
```

```yaml
# stack.yaml
resolver: nightly-2018-03-10
extra-deps:
- conduit-1.3.0
- resourcet-1.2.0
- conduit-extra-1.3.0
- cereal-conduit-0.8.0
- stm-conduit-4.0.0
- conduit-combinators-1.3.0
```
